### ISSUE TITLE
c=============333=====3=3========333333

### ISSUE THREAD

**Issue by arvo95** [dmednis/malloc-algorithm-visualizer#8]
───────────────▄▄▄▄▄▄▄─────────── 
─────────────▄█▒▒▒█▒▒▒█▄───────── 
────────────█▒▒▒▒▒▒▒▒▒▒█▌──────── 
───────────█▒▒▒▒▒▒▒▒▒▒▒▒█──────── 
───────────█▒▒▒▒▒▒▒▒▒▒▒█▌──────── 
──────────██████████████───────── 
──────────█▒▒▒▒▒▒▒▒▒▒▒█▌───────── 
─────────█▒████▒████▒▒█────────── 
─────────█▒▒▒▒▒▒▒▒▒▒▒▒█────────── 
─────────█▒────▒▒────▒█▌───────── 
─────────█▒██──▒▒██──▒▒█───────── 
─────────█▒────▒▒────▒▒█───────── 
────────▄█▒▒▒▒▒▒▒▒▒▒▒▒▒██──────── 
───────██▒▒▒████████▒▒▒▒██─────── 
─────██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██───── 
───██▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒██─── 
─██▒▒▒▒▒▒▒▒▒▒▒▒██▒▒▒▒▒▒▒▒▒▒▒▒▓██─ 
█▒▒▒▒▒▒▒▒▒▒▒▒▒██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██ 
█▒▒▒▒▒▒▒▒▒▒▒▒▓█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█ 
█▓▒▒▒▒▒▒▒▒▒▒▒▓██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█ 
▀██▒▒▒▒▒▒▒▒▒▒▒▓██▒▒▒▒▒▒▒▒▒▒▒▒▒██▀ 
──██▒▒▒▒▒▒▒▒▒██████▒▒▒▒▒▒▒▒▒▒██── 
───███████████▌▌▌▌████████████───

Mr. Dick has visited this repository. If you do not share this in 69 hours, 420 new issues will appear on this repo. Maintain good code quality, share mr. Dick.

**Comment by power-hunger** [comment]
# **CRITICAL ISSUE!**
